// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sc2Otter.Data;

#nullable disable

namespace Sc2Otter.Data.Migrations
{
    [DbContext(typeof(ScoutDbContext))]
    [Migration("20260705231245_AddFullMatchData")]
    partial class AddFullMatchData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Sc2Otter.Core.Models.MatchRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullMatchData")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameMode")
                        .HasColumnType("TEXT");

                    b.Property<string>("MapName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MyAvgMineralIncome")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MyAvgUnspentMinerals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MyRace")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MySupplyBlockTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MyUnitsMade")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MyWorkersCreated")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OpponentAvgMineralIncome")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OpponentAvgUnspentMinerals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentRace")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OpponentSupplyBlockTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentUnitsMade")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OpponentWorkersCreated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OpponentId");

                    b.ToTable("MatchRecords");
                });

            modelBuilder.Entity("Sc2Otter.Core.Models.Opponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Race")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Opponents");
                });

            modelBuilder.Entity("Sc2Otter.Core.Models.OpponentNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OpponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OpponentId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Sc2Otter.Core.Models.OpponentTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FF6B35",
                            Name = "cheese"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#4ECDC4",
                            Name = "macro"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#FF1744",
                            Name = "aggressive"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#42A5F5",
                            Name = "defensive"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#FF5252",
                            Name = "all-in"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#FFC107",
                            Name = "timing attack"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#FF9800",
                            Name = "cannon rush"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#E040FB",
                            Name = "proxy"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#66BB6A",
                            Name = "fast expand"
                        },
                        new
                        {
                            Id = 10,
                            Color = "#78909C",
                            Name = "turtle"
                        });
                });

            modelBuilder.Entity("Sc2Otter.Core.Models.OpponentTagAssignment", b =>
                {
                    b.Property<int>("OpponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("OpponentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("OpponentTagAssignment");
                });

            modelBuilder.Entity("Sc2Otter.Core.Models.MatchRecord", b =>
                {
                    b.HasOne("Sc2Otter.Core.Models.Opponent", "Opponent")
                        .WithMany("MatchRecords")
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opponent");
                });

            modelBuilder.Entity("Sc2Otter.Core.Models.OpponentNote", b =>
                {
                    b.HasOne("Sc2Otter.Core.Models.Opponent", "Opponent")
                        .WithMany("Notes")
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opponent");
                });

            modelBuilder.Entity("Sc2Otter.Core.Models.OpponentTagAssignment", b =>
                {
                    b.HasOne("Sc2Otter.Core.Models.Opponent", "Opponent")
                        .WithMany("TagAssignments")
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sc2Otter.Core.Models.OpponentTag", "Tag")
                        .WithMany("TagAssignments")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opponent");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Sc2Otter.Core.Models.Opponent", b =>
                {
                    b.Navigation("MatchRecords");

                    b.Navigation("Notes");

                    b.Navigation("TagAssignments");
                });

            modelBuilder.Entity("Sc2Otter.Core.Models.OpponentTag", b =>
                {
                    b.Navigation("TagAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
